### ISSUE TITLE
Transparent header

### ISSUE THREAD

**Issue by pedr0luiz** [tsvillain/Wallbay#9]
The should header be transparent like this?

![Simulator Screen Shot - iPhone 8 - 2021-11-02 at 11 54 43](https://user-images.githubusercontent.com/38326603/139871828-0ce1c494-e354-4370-b868-3d80c0ffa679.png)

**Comment by tsvillain** [comment]
@pedr0luiz No, it's not transparent in appTitle is white in color.
As much as I know in the last build available on PlayStore it's black in color.
Which device are you using to test / run in debug?

**Comment by pedr0luiz** [comment]
> @pedr0luiz No, it's not transparent in appTitle is white in color. As much as I know in the last build available on PlayStore it's black in color. Which device are you using to test / run in debug?

The appBar background color is [transparent](https://github.com/tsvillain/Wallbay/blob/master/lib/Screens/HomePage.dart#L62) and the Text/icon color is white. 
I'm running in iPhone 8 simulator. Should we change the appBar background color to the same as the home screen and the text/icons color to black?

**Comment by tsvillain** [comment]
Will check in iOS at my end. You can work on #6 issue.

**Comment by pedr0luiz** [comment]
@tsvillain any updates on this?

**Comment by tsvillain** [comment]
@pedr0luiz Sorry for the delay was busy with other work.
I checked and realized it's showing text and icon white in all AppBar.
Your above suggestions are correct you can make the text black but keep the background as it is.
